server:
  port: 9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

spring:
  application:
    name: ms-bet
  data:
    mongodb:
      database: test-mongo
      port: 27017
  main:
    webApplicationType: reactive

